/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shipsBeta2;

import java.awt.Font;

/**
 *
 * @author Qbass
 */
public class TheMainFrame extends javax.swing.JFrame {
    
    public static int[] shipsAvailable = new int[4];

    
    private void initShips(int gametype){
        switch(gametype){
            case 0:{    //standard game
                TheMainFrame.shipsAvailable[0] = 4;
                TheMainFrame.shipsAvailable[1] = 3;
                TheMainFrame.shipsAvailable[2] = 2;
                TheMainFrame.shipsAvailable[3] = 1;
            }
        }
    }
    /**
     * Creates new form NewJFrame
     */
    public TheMainFrame() {
        initComponents();
        pGame.putClientProperty("ship", -1);
        this.initShips(0);
        this.refreshCounts();
    }
    
    private void refreshCounts(){
        this.lShipDestroyerCount.setText(String.valueOf(shipsAvailable[0]));
        this.lShipCruiserCount.setText(String.valueOf(shipsAvailable[1]));
        this.lShipBattleshipCount.setText(String.valueOf(shipsAvailable[2]));
        this.lShipCarrierCount.setText(String.valueOf(shipsAvailable[3]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConnect = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        pGame = new MainPanel();
        pGameInfo = new javax.swing.JPanel();
        lShipsAvailable = new javax.swing.JLabel();
        lShipCruiser = new javax.swing.JLabel();
        lShipDestroyer = new javax.swing.JLabel();
        lShipBattleship = new javax.swing.JLabel();
        lShipCarrier = new javax.swing.JLabel();
        lShipDestroyerCount = new javax.swing.JLabel();
        lShipCruiserCount = new javax.swing.JLabel();
        lShipBattleshipCount = new javax.swing.JLabel();
        lShipCarrierCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..::The Ships Beta 0.02b::..");

        bConnect.setText("Connect");
        bConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnectActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        pGame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pGameMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout pGameLayout = new javax.swing.GroupLayout(pGame);
        pGame.setLayout(pGameLayout);
        pGameLayout.setHorizontalGroup(
            pGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        pGameLayout.setVerticalGroup(
            pGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lShipsAvailable.setText("Ships available:");

        lShipCruiser.setText("Cruisers(3): ");
        lShipCruiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lShipCruiserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lShipCruiserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lShipCruiserMouseExited(evt);
            }
        });

        lShipDestroyer.setText("Destroyers(2):");
        lShipDestroyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lShipDestroyerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lShipDestroyerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lShipDestroyerMouseExited(evt);
            }
        });

        lShipBattleship.setText("Battleships(4):");
        lShipBattleship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lShipBattleshipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lShipBattleshipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lShipBattleshipMouseExited(evt);
            }
        });

        lShipCarrier.setText("Aircraft Carriers(5): ");
        lShipCarrier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lShipCarrierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lShipCarrierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lShipCarrierMouseExited(evt);
            }
        });

        lShipDestroyerCount.setText("4");

        lShipCruiserCount.setText("3");

        lShipBattleshipCount.setText("2");

        lShipCarrierCount.setText("1");

        javax.swing.GroupLayout pGameInfoLayout = new javax.swing.GroupLayout(pGameInfo);
        pGameInfo.setLayout(pGameInfoLayout);
        pGameInfoLayout.setHorizontalGroup(
            pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGameInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGameInfoLayout.createSequentialGroup()
                        .addComponent(lShipsAvailable)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pGameInfoLayout.createSequentialGroup()
                        .addGroup(pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lShipCarrier, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(lShipBattleship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lShipCruiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lShipDestroyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lShipBattleshipCount)
                            .addComponent(lShipCruiserCount)
                            .addComponent(lShipDestroyerCount)
                            .addComponent(lShipCarrierCount))))
                .addContainerGap())
        );
        pGameInfoLayout.setVerticalGroup(
            pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGameInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pGameInfoLayout.createSequentialGroup()
                        .addComponent(lShipDestroyerCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipCruiserCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipBattleshipCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipCarrierCount))
                    .addGroup(pGameInfoLayout.createSequentialGroup()
                        .addComponent(lShipsAvailable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipDestroyer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipCruiser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipBattleship)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lShipCarrier)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bExit))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pGameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConnect)
                    .addComponent(bExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pGameInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void lShipCarrierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCarrierMouseEntered
        lShipCarrier.setFont(lShipCarrier.getFont().deriveFont(Font.BOLD));                                       
        lShipCarrierCount.setFont(lShipCarrierCount.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_lShipCarrierMouseEntered

    private void lShipCarrierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCarrierMouseExited
        if(addShipSelected != 3){
            lShipCarrier.setFont(lShipCarrier.getFont().deriveFont(Font.PLAIN));                                     
            lShipCarrierCount.setFont(lShipCarrierCount.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_lShipCarrierMouseExited

    private void lShipBattleshipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipBattleshipMouseEntered
        lShipBattleship.setFont(lShipBattleship.getFont().deriveFont(Font.BOLD));                                        
        lShipBattleshipCount.setFont(lShipBattleshipCount.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_lShipBattleshipMouseEntered

    private void lShipBattleshipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipBattleshipMouseExited
        if(addShipSelected != 2){
            lShipBattleship.setFont(lShipBattleship.getFont().deriveFont(Font.PLAIN));
            lShipBattleshipCount.setFont(lShipBattleshipCount.getFont().deriveFont(Font.PLAIN));
        }                                     
    }//GEN-LAST:event_lShipBattleshipMouseExited

    private void lShipCruiserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCruiserMouseEntered
        lShipCruiser.setFont(lShipCruiser.getFont().deriveFont(Font.BOLD));                                      
        lShipCruiserCount.setFont(lShipCruiserCount.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_lShipCruiserMouseEntered

    private void lShipCruiserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCruiserMouseExited
        if(addShipSelected != 1){
            lShipCruiser.setFont(lShipCruiser.getFont().deriveFont(Font.PLAIN));                                    
            lShipCruiserCount.setFont(lShipCruiserCount.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_lShipCruiserMouseExited

    private void lShipDestroyerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipDestroyerMouseEntered
        lShipDestroyer.setFont(lShipDestroyer.getFont().deriveFont(Font.BOLD));                                        
        lShipDestroyerCount.setFont(lShipDestroyerCount.getFont().deriveFont(Font.BOLD));
    }//GEN-LAST:event_lShipDestroyerMouseEntered

    private void lShipDestroyerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipDestroyerMouseExited
        if(addShipSelected != 0){
            lShipDestroyer.setFont(lShipDestroyer.getFont().deriveFont(Font.PLAIN));                                    
            lShipDestroyerCount.setFont(lShipDestroyerCount.getFont().deriveFont(Font.PLAIN));
        }
    }//GEN-LAST:event_lShipDestroyerMouseExited

    private void bConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnectActionPerformed
        bConnect.setText("Connect (N/A)");
    }//GEN-LAST:event_bConnectActionPerformed
    int addShipSelected = -1;

    private void addSelectShip(int ship){        
        pGame.putClientProperty("ship", ship);
        lShipDestroyer.setFont(lShipDestroyer.getFont().deriveFont(Font.PLAIN));                                    
        lShipDestroyerCount.setFont(lShipDestroyerCount.getFont().deriveFont(Font.PLAIN));
        lShipCruiser.setFont(lShipCruiser.getFont().deriveFont(Font.PLAIN));                                    
        lShipCruiserCount.setFont(lShipCruiserCount.getFont().deriveFont(Font.PLAIN));
        lShipBattleship.setFont(lShipBattleship.getFont().deriveFont(Font.PLAIN));                                    
        lShipBattleshipCount.setFont(lShipBattleshipCount.getFont().deriveFont(Font.PLAIN));
        lShipCarrier.setFont(lShipCarrier.getFont().deriveFont(Font.PLAIN));                                    
        lShipCarrierCount.setFont(lShipCarrierCount.getFont().deriveFont(Font.PLAIN));
        switch(ship){
            case 0 :{
                lShipDestroyer.setFont(lShipDestroyer.getFont().deriveFont(Font.BOLD));                                        
                lShipDestroyerCount.setFont(lShipDestroyerCount.getFont().deriveFont(Font.BOLD));
                break;
            }
            case 1 :{
                lShipCruiser.setFont(lShipCruiser.getFont().deriveFont(Font.BOLD));                                    
                lShipCruiserCount.setFont(lShipCruiserCount.getFont().deriveFont(Font.BOLD));
                break;
            }
            case 2 :{                
                lShipBattleship.setFont(lShipBattleship.getFont().deriveFont(Font.BOLD));                                    
                lShipBattleshipCount.setFont(lShipBattleshipCount.getFont().deriveFont(Font.BOLD));
                break;
            }
            case 3 :{
                lShipCarrier.setFont(lShipCarrier.getFont().deriveFont(Font.BOLD));                                    
                lShipCarrierCount.setFont(lShipCarrierCount.getFont().deriveFont(Font.BOLD));
                break;
            }
                
        }
        this.refreshCounts();
    }
    private void lShipDestroyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipDestroyerMouseClicked
        // TODO add your handling code here:
        if(addShipSelected != 0) addShipSelected = 0; else addShipSelected = -1;
        addSelectShip(addShipSelected);
    }//GEN-LAST:event_lShipDestroyerMouseClicked

    private void lShipCruiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCruiserMouseClicked
        // TODO add your handling code here:
        if(addShipSelected != 1) addShipSelected = 1; else addShipSelected = -1;
        addSelectShip(addShipSelected);
    }//GEN-LAST:event_lShipCruiserMouseClicked

    private void lShipBattleshipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipBattleshipMouseClicked
        // TODO add your handling code here:
        if(addShipSelected != 2) addShipSelected = 2; else addShipSelected = -1;
        addSelectShip(addShipSelected);
    }//GEN-LAST:event_lShipBattleshipMouseClicked

    private void lShipCarrierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lShipCarrierMouseClicked
        // TODO add your handling code here:
        if(addShipSelected != 3) addShipSelected = 3; else addShipSelected = -1;
        addSelectShip(addShipSelected);
    }//GEN-LAST:event_lShipCarrierMouseClicked

    private void pGameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pGameMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConnect;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel lShipBattleship;
    private javax.swing.JLabel lShipBattleshipCount;
    private javax.swing.JLabel lShipCarrier;
    private javax.swing.JLabel lShipCarrierCount;
    private javax.swing.JLabel lShipCruiser;
    private javax.swing.JLabel lShipCruiserCount;
    private javax.swing.JLabel lShipDestroyer;
    private javax.swing.JLabel lShipDestroyerCount;
    private javax.swing.JLabel lShipsAvailable;
    private javax.swing.JPanel pGame;
    private javax.swing.JPanel pGameInfo;
    // End of variables declaration//GEN-END:variables
}
